### ISSUE TITLE
Public address characters are very long

### ISSUE THREAD

**Issue by decentralandmiguel** [decentraland/profile#100]
** What is happening?**
    * Public wallet address is very long. The ideal way to show this is to show the first 4 characters and the last 4 as wallets do. It doesn't make sense to show more than that. 
** What should happen?**
* Show it like in the designs
![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/e2fd060e-2d4d-4f20-b120-783d49eda76b)

![image.png](https://images.zenhubusercontent.com/64d100d037a41802ee2a6fe8/e80ca6ee-a303-4ca4-a898-b8c1dabbd1ef)

**Comment by LautaroPetaccio** [comment]
Hi Miki!
I have grabbed the four first characters of the wallet address and the last 4 as the design shows, but I've not counted the `0x` part of the address due to it not being part of the address itself.
[Screenshot 2023-08-07 at 16.58.54.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/6dc4b29b-737d-4742-89a2-80198a06c6b9)
Is it ok?

**Comment by decentralandmiguel** [comment]
Its perfect!
